// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCHL76aPslEgUFMFMcYJKKBKLaVWIL2xQ',
    appId: '1:802032184337:web:8cb2cb554b1d10c20455b0',
    messagingSenderId: '802032184337',
    projectId: 'fir-9ec0d',
    authDomain: 'fir-9ec0d.firebaseapp.com',
    storageBucket: 'fir-9ec0d.appspot.com',
    measurementId: 'G-GNV1T7K3GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTx8q_7hUTp9rbUKB78xLLFMllILka_BI',
    appId: '1:802032184337:android:745fa84eb297d0300455b0',
    messagingSenderId: '802032184337',
    projectId: 'fir-9ec0d',
    storageBucket: 'fir-9ec0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU_VqF2sUxCBX46z67vkSp2P-09tg5D4M',
    appId: '1:802032184337:ios:9be9c329be49fb730455b0',
    messagingSenderId: '802032184337',
    projectId: 'fir-9ec0d',
    storageBucket: 'fir-9ec0d.appspot.com',
    androidClientId: '802032184337-qaae20e1romalnj4p32oqb0qjpeeo1kv.apps.googleusercontent.com',
    iosClientId: '802032184337-84uf8jngkjr8dalqrsqnlh5ccl3fvotc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
